/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Javi Cordero
 */
public class FRM_Principal extends javax.swing.JFrame
{
    private ArrayList<Integer> numeros;
    
    private int[] arregloDatos;
    
    public FRM_Principal() 
    {
        initComponents();
        arregloDatos = new int[]{58, 12, 0, 98, 30, 2, 7, 41, 45, 19};
        numeros = new ArrayList<>();
        llenarArrayList();
        
        //insertarDatos();
        reiniciar();
        setLocationRelativeTo(null);
    }//Fin del constructor.
    
    public void llenarArrayList()
    {
        int tamanio = arregloDatos.length;
        
        for(int i=0; i<tamanio; i++)
        {
            numeros.add(arregloDatos[i]);
        }
    }
    public void reiniciarArreglo()
    {
        int tamanio = numeros.size();
        
        for(int i=0; i<tamanio; i++)
        {
            arregloDatos[i] = numeros.get(i);
        }
    }
    public void insertarDatos()
    {
        arregloDatos = new int[10];
        int tamanio = arregloDatos.length;
        
        for(int contador=0; contador<tamanio; contador++)
        {
            arregloDatos[contador] = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el dato #" + (contador+1), "", JOptionPane.PLAIN_MESSAGE));
        }
        llenarArrayList();
    }//Fin del metodo insertarDatos.
    
    public void reiniciar()
    {
        grupoBotones.clearSelection();
        reiniciarArreglo();
    }//Fin del metodo reiniciar.
    
    public int[] devolverArreglo()
    {
        return arregloDatos;
    }//Fin del metodo devolverArreglo.
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        label_Titulo = new javax.swing.JLabel();
        radioBoton_Intercambio = new javax.swing.JRadioButton();
        radioBoton_Seleccion = new javax.swing.JRadioButton();
        radioBoton_Shell = new javax.swing.JRadioButton();
        radioBoton_Merge = new javax.swing.JRadioButton();
        radioBoton_Quicksort = new javax.swing.JRadioButton();
        btn_Ver = new javax.swing.JButton();
        radioBoton_Burbuja = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Titulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Titulo.setText("Elija el algoritmo que desea ver");

        grupoBotones.add(radioBoton_Intercambio);
        radioBoton_Intercambio.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Intercambio.setText("Intercambio");

        grupoBotones.add(radioBoton_Seleccion);
        radioBoton_Seleccion.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Seleccion.setText("Seleccion");

        grupoBotones.add(radioBoton_Shell);
        radioBoton_Shell.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Shell.setText("Shell");

        grupoBotones.add(radioBoton_Merge);
        radioBoton_Merge.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Merge.setText("Merge");

        grupoBotones.add(radioBoton_Quicksort);
        radioBoton_Quicksort.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Quicksort.setText("Quicksort");

        btn_Ver.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btn_Ver.setText("Ver algoritmo");
        btn_Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerActionPerformed(evt);
            }
        });

        grupoBotones.add(radioBoton_Burbuja);
        radioBoton_Burbuja.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        radioBoton_Burbuja.setText("Burbuja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBoton_Burbuja)
                            .addComponent(radioBoton_Seleccion)
                            .addComponent(radioBoton_Intercambio)
                            .addComponent(radioBoton_Shell)
                            .addComponent(radioBoton_Merge)
                            .addComponent(radioBoton_Quicksort)
                            .addComponent(btn_Ver))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label_Titulo)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Intercambio)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Seleccion)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Shell)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Merge)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Quicksort)
                .addGap(18, 18, 18)
                .addComponent(radioBoton_Burbuja)
                .addGap(18, 18, 18)
                .addComponent(btn_Ver)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerActionPerformed
        if(radioBoton_Intercambio.isSelected())
        {
            FRM_Intercambio intercambio = new FRM_Intercambio(this, true);
            intercambio.setVisible(true);
        }
        if(radioBoton_Seleccion.isSelected())
        {
            FRM_Seleccion seleccion = new FRM_Seleccion(this, true);
            seleccion.setVisible(true);
        }
        if(radioBoton_Quicksort.isSelected())
        {
            
        }
        if(radioBoton_Shell.isSelected())
        {
            FRM_Shell shell = new FRM_Shell(this, true);
            shell.setVisible(true);
        }
        if(radioBoton_Merge.isSelected())
        {
            
        }
        if(radioBoton_Burbuja.isSelected())
        {
            FRM_Burbuja burbuja = new FRM_Burbuja(this, true);
            burbuja.setVisible(true);
        }
    }//GEN-LAST:event_btn_VerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ver;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel label_Titulo;
    private javax.swing.JRadioButton radioBoton_Burbuja;
    private javax.swing.JRadioButton radioBoton_Intercambio;
    private javax.swing.JRadioButton radioBoton_Merge;
    private javax.swing.JRadioButton radioBoton_Quicksort;
    private javax.swing.JRadioButton radioBoton_Seleccion;
    private javax.swing.JRadioButton radioBoton_Shell;
    // End of variables declaration//GEN-END:variables
}
